# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false

contact_links:
  - name: MermaidPad Discussions
    url: https://github.com/udlose/MermaidPad/discussions
    about: Please use Discussions for questions, ideas, help requests, or general conversation. Only open issues for actual bugs or feature requests.
